### ISSUE TITLE
Stopped detecting controllers after Manjaro update.

### ISSUE THREAD

**Issue by Git-Forked** [frealgagu/archlinux.antimicrox#2]
Previous to the Manjaro update AntiMicroX was detecting my XBOX controller.  After the update there is no controller detection, even when refreshing multiple times.  Rebuilding only solves the issue until a reboot, then the issue reappears.  I would hope I don't have to rebuild every time the computer boots.  Perhaps there is something in the code that can be updated to overcome this.  Thank you.

**Comment by frealgagu** [comment]
This repository is only for building the archlinux package. Please open an issue in: https://github.com/AntiMicroX/antimicroX
